spring:
  application:
    name: config

#eureka配置
eureka:
  client:
    service-url:
      #eureka单机配置
      #defaultZone: http://localhost:8761/eureka
      #eureka单机配置集群配置
      defaultZone: http://mall.eureka8761.com:8761/eureka,http://mall.eureka8762.com:8762/eureka,http://mall.eureka8763.com:8763/eureka

